# Generated by Django 3.2.3 on 2021-05-29 11:21

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('mining_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.miningfarm')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('bio', models.TextField(null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='mining_farm/logo')),
                ('investment', models.ManyToManyField(to='invest.Investment')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
