# Generated by Django 3.2.3 on 2021-05-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
