# Generated by Django 3.2.3 on 2021-05-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MiningOption',
            new_name='InvestmentOption',
        ),
        migrations.RemoveField(
            model_name='miningfarm',
            name='mining_options',
        ),
        migrations.AddField(
            model_name='miningfarm',
            name='investment_options',
            field=models.ManyToManyField(to='farm.InvestmentOption'),
        ),
    ]
